### ISSUE TITLE
View information about the organizations listed

### ISSUE THREAD

**Issue by cernst122** [Spelman-College/spelman-dashboard#19]
- [x] Requirement 1: Information about the organizations should only be accessible via user interaction (e.g. click, preview hover)
- [x] Requirement 2: Upon user interaction, the following is viewable: website, founding date, founder, STEM focus

**Comment by cernst122** [comment]
Backend prototype should parse this info from a dummy sheet and display in an arbitrary UI element.

**Comment by isaac-looker** [comment]
https://github.com/Spelman-College/spelman-dashboard/pull/45
