### ISSUE TITLE
Download list of personalized organizations for offline use

### ISSUE THREAD

**Issue by cernst122** [Spelman-College/spelman-dashboard#22]
- [ ] Requirement 1: Upon viewing the data, the user sees the option to download a CSV file
- [ ] Requirement 2: User clicks button to download
- [ ] Requirement 3: Visual response is provided of download attempt

**Comment by cernst122** [comment]
Blocked on backend implementation of https://github.com/Spelman-College/spelman-dashboard/issues/19.

**Comment by isaac-looker** [comment]
https://github.com/Spelman-College/spelman-dashboard/pull/48

**Comment by isaac-looker** [comment]
by 'personalized', do we mean the user selects organizations from the portal and only the selected are downloaded? Or are we just downloading all of them?

**Comment by isaac-looker** [comment]
I found a comment about this feature being moved to a future iteration.

**Comment by cernst122** [comment]
Good catch, I'll remove 'personalized' from the bug title.
