### ISSUE TITLE
Import table #1 (STEM Degrees Conferred by Level)

### ISSUE THREAD

**Issue by cernst122** [Spelman-College/spelman-dashboard#25]
See import list at #21

**Comment by cernst122** [comment]
This has been flagged as a set we're interested in for a pre-loaded visualization: "What fraction of STEM degrees are granted to Black women, compared to other demographic groups? How has this changed over time?  
     Show this as a trend chart. "

Let's prioritize this for upload along with the other flagged sets.

**Comment by isaac-looker** [comment]
Is there a Sheet with `processed_csv` for this dataset?

**Comment by cernst122** [comment]
https://docs.google.com/spreadsheets/d/1EKFKSF2Ex8rd-irm83qDqLwTYMOyxWZTg1gqXq-n8lE/edit?resourcekey=0-JZkTIVKk-BotO_lLeExA9g#gid=1933997560
