### ISSUE TITLE
Import table #2 (Salaries)

### ISSUE THREAD

**Issue by cernst122** [Spelman-College/spelman-dashboard#26]
See import list at #21

**Comment by amiersmith** [comment]
processed sheet: https://docs.google.com/spreadsheets/d/1qHEkQzdQCAva6WpX4cpHeQUTOZpghmX2-kJ94MRoxaY/edit?usp=sharing&resourcekey=0-5J7J-ba51Q_NRmAQ1lh_Fw

import doc: https://docs.google.com/document/d/1UIXk-J6r-IGRlznEs0GsjoGZh8IBBrcKY7J3IfS6qME/edit

**Comment by cernst122** [comment]
This has been flagged as a set we're interested in for a pre-loaded visualization: "How much do Black women with a STEM degree make, compared to other demographic groups? How has this changed over time?" 

Let's prioritize this for upload along with the other flagged sets.

UXR is also interested in map data for this question if possible. If we're able to identify a map set, we'll open a new issue to track it.
